### ISSUE TITLE
Alpha & Beta Defaults

### ISSUE THREAD

**Issue by jeremypennycook** [michaelengland/FlipTheSwitch#34]
Both Alpha and Beta should have configuration options available for individual feature flags.

Both should default to the assumed set of feature toggles indicative of the next release (ie pulled from master).

A user can override these defaults locally. 

Flags toggled to a state different than the default by a user should persist when upgrading to a new version.

Nice to have: There should be a button which resets the toggles to the state provided from master.

**Comment by jeremypennycook** [comment]
@michaelengland I cannot add labels or milestones.

**Comment by michaelengland** [comment]
Basically, all these should currently be possible, but the nice-to-have is what this needs to be :).

Would be great to add a 'reset' button to the configuration screen. That way, if you've been turning a lot on/off you can go back to what's live for testing. :+1:

**Comment by michaelengland** [comment]
@FrauR WDYT? Maybe add this to the next release? I think there's already the ability to reset features, so would be great to do this too.

**Comment by michaelengland** [comment]
Reset button added.
