### ISSUE TITLE
Subfeature should be added to the generated plist in the correct hierarchy

### ISSUE THREAD

**Issue by FrauR** [michaelengland/FlipTheSwitch#52]
The sub feature `disabled_subfeature` in [`ExpectedFeatures.plist`](https://github.com/michaelengland/FlipTheSwitch/blob/master/spec/resources/ExpectedFeatures.plist) is  one level too high in the hierarchy. So the test is passing for the wrong reason.

Related to #51

**Comment by michaelengland** [comment]
Wel volunteered :D

**Comment by FrauR** [comment]
Thanks

**Comment by FrauR** [comment]
Sorry, that was a misunderstanding from my side. The plist was never supposed to have cascading structure.
